app/blueprints/event_datasource.py
# Blueprint for handling events

from flask import request, Blueprint
from flask.ext.login import login_required,current_user
from app.models.querymachine import QueryMachine
from app.models.eventunit import EventUnit
from app.models.event import Event
from app.models.layer import Layer
from app.models.playlist import Playlist
from app.models.user import Collaboration
import json
from werkzeug import secure_filename
from app.models.querymachine import DBSessionMaker
import hashlib

# Amazon Simple Storage Service
from boto.s3.connection import S3Connection
from config import AWSAccessKeyId,AWSSecretKey,AWS_S3_Bucket
from boto.s3.key import Key

event_datasource = Blueprint('event_datasource', __name__, template_folder='templates')

@event_datasource.route('/get/events/single/json')
def get_single_event_using_query_machine():
    """
    Find a single event using event id. The event is returned as JSON string.
    :rtype: str
    :return: JSON string of the found event object
    """

    id = request.args.get('ID', 1)
    result = QueryMachine.get_single_event_using_query_machine(id)
    return json.dumps(result.serializeJSON) if result else json.dumps("{}")

@event_datasource.route('/get/events/json')
def getEventsUsingQueryMachine():
    """
    Find events with defined search options using GET method
    :returns: JSON of found events
    :rtype: str
    """

    # Never trust the input from users, parse integers from all kinds of input with defaults integers
    how_many = request.args.get('howmany', '5')
    min_significance = request.args.get('minsignificance', '3')
    max_significance = request.args.get('maxsignificance', '10')
    start_date = request.args.get('startdate', '0')
    end_date = request.args.get('enddate', '1')
    search_text = request.args.get('searchtext', '')

    categories = request.args.get('categories', '').split(",")
    categories = filter(lambda x: x.isdigit(), categories)

    # Validate numerical input. Force the values inside defined ranges
    how_many = min(max(3 if not how_many.isdigit() else int(how_many), 1), 50)
    min_significance = min(max(3 if not min_significance.isdigit() else int(min_significance), 1), 10)
    max_significance = min(max(max(10 if not max_significance.isdigit() else int(max_significance), 1), max_significance), 10)

    results = QueryMachine.queryEventsBetween(how_many, min_significance, max_significance, start_date, end_date, search_text, categories)
    return json.dumps(map(lambda x: x.serializeJSON if x and type(x) is Event else "{}", results))

@event_datasource.route('/get/units/json', methods=['GET','POST'])
def getUnitInformationInJSON():
    """
    Fetch unit data using JSON-format. Supports a single retrieval and multiple at the same time. However,
    do not trust that the units are always available.
    :returns: json dump of final data
    """

    selected_units = []
    if request.method == "GET":
        selected_units = request.args.get('selected_units','[]')
    if request.method == "POST":
        selected_units = request.form['selected_units']

    serialize_unit_if_possible = lambda x: x.serializeJSON if x and type(x) is EventUnit else "{}"

    if selected_units.isdigit():
        final_data = serialize_unit_if_possible(QueryMachine.singleUnitData(int(selected_units)))
    else:
        selected_units = json.loads(selected_units)
        final_data = map(lambda x: serialize_unit_if_possible(QueryMachine.singleUnitData(x)), selected_units)

    return json.dumps(final_data)

@event_datasource.route('/search/events/json')
def searchEvents():
    """
    Search events using a keyword. Return only actual found Event objects
    :returns: JSON array of found events
    """

    serialize_event_if_possible = lambda x: x.serializeJSON if x and type(x) is Event else "{}"

    search_text = request.args.get('searchText', '')
    if len(search_text) > 2:
        return json.dumps(map(lambda x: serialize_event_if_possible(x), QueryMachine.searchEvents(search_text)))
    else:
        return json.dumps([])

@event_datasource.route('/search/units/json')
def searchUnits():
    """
    Search units using a searchtext keyword
    :returns: JSON array of found units
    """
    search_text = request.args.get('searchText', '')
    if len(search_text) > 2:
        search_results = QueryMachine.searchUnits(search_text)
        return json.dumps(map(lambda x: x.serializeJSON if x else "{}", search_results))
    else:
        return json.dumps([])

@event_datasource.route('/set/event', methods=['GET','POST'])
@login_required
def setEvent():
    if request.method == 'POST':
        QueryMachine.createEvent(
            request.form['selcats'],
            request.form['selected_preset_topics'],
            author=current_user._get_current_object().id,
            start=request.form['start'],
            end=request.form['stop'],
            title=request.form['title'],
            description=request.form['desc'],
            wikilink=request.form['wiki'],
            significance=request.form['sig'],
            data=request.form['data'],
            filename=request.form['filename'],
            incertitude=request.form['incertitude'],
            incertitude_type=request.form['incertitude_type'],
            visibility_type=request.form['visibility_type']
        )

        return "1"
    return ""

@event_datasource.route('/update/event', methods=['GET', 'POST'])
@login_required
def updateEvent():

    if request.method == 'POST':

        author = current_user._get_current_object().id
        uid = request.form['id']

        # Does the user have correct rights to edit? This means either of
        # being the original author or having privilege of collaboration.
        if QueryMachine.check_user_privilege(author, uid, 0):


            QueryMachine.updateEvent(
                request.form['selcats'],
                request.form['selected_preset_topics'],
                start=request.form['start'],
                end=request.form['stop'],
                title=request.form['title'],
                description=request.form['desc'],
                wikilink=request.form['wiki'],
                significance=request.form['sig'],
                data=request.form['data'],
                id=uid,
                filename=request.form['filename'],
                incertitude=request.form['incertitude'],
                incertitude_type=request.form['incertitude_type'],
                visibility_type=request.form['visibility_type']
            )

            return "H"

    return ""

@event_datasource.route('/delete/event', methods=['GET', 'POST'])
@login_required
def deleteEvent():
    if request.method == 'POST':
        author = current_user._get_current_object().id
        uid = request.form['id']
        with DBSessionMaker() as conn:
            event = Event.query.filter_by(id=uid).first()

            # Check if the user has correct rights to edit?
            if event is not None and event.author == author:
                conn.delete(event)
                conn.commit()

        return "ok"
    return ""

@event_datasource.route('/set/unit/image', methods=['GET','POST'])
@login_required
def uploadUnitImage():
    """
    Upload unit images to the Amazon S3 with a filename, which is a hash
    that is calculated from the image content. This can potentially remove
    duplicates of identical images from users.
    """

    # Create a set of allowed extensions.
    ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

    def allowed_file(filename):
        return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

    if request.method == 'POST':
        file = request.files['unitMovementImage_'+request.args.get('dir')]

        if file and allowed_file(file.filename):

            filename = secure_filename(file.filename)
            fileExtension = filename.rsplit('.', 1)[1]

            # Open a connection to Amazon S3
            conn = S3Connection(AWSAccessKeyId, AWSSecretKey)

            # Open the existing bucket
            bucket = conn.get_bucket(AWS_S3_Bucket)

            # Initialize a key for a single file
            k = Key(bucket)

            # Read the file contents and calculate the corresponding hash
            image_data = file.read()
            image_hash = hashlib.sha1(image_data).hexdigest()

            # Set metadata
            k.set_metadata("uploader_id", current_user._get_current_object().id)

            # Set hash filename with the given file extension. The filename starts
            # with user id, has a random filename part and has the original picture
            # file format extension. This allows user-specific searches with common prefix.
            k.key = '{2}_{0}.{1}'.format(image_hash, fileExtension,current_user._get_current_object().id)

            print "Uploaded image filename:",k.key

            k.set_contents_from_string(image_data)

            return "http://{1}.s3.amazonaws.com/{0}".format(k.key, AWS_S3_Bucket)

    return 'Upload error'

@event_datasource.route('/set/unit', methods=['GET', 'POST'])
@login_required
def setUnit():
    if request.method == "POST":
        with DBSessionMaker() as conn:
            unit = EventUnit(
                author=current_user._get_current_object().id,
                appears=request.form['start'],
                disappears=request.form['stop'],
                title=request.form['title'],
                location=request.form['location'],
                description=request.form['desc'],
                wikilink=request.form['wikilink'],
                filename=request.form['filename'],
                imageData=request.form['imageData']
            )
            conn.add(unit)
            conn.commit()
        return "ok"
    return ""

@event_datasource.route('/update/unit', methods=['GET', 'POST'])
@login_required
def updateUnit():
    if request.method == "POST":

app/templates/windowCollaborationRights.html
<!-- Editor for collaboration rights -->
<div id="unitCollaborationEditForm" class="modal hide fade" tabindex="-1" data-width="80%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Collaborators</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <div class="span4">
                <p>
                    You may given collaboration rights for content to users
                    with specified user names. This means that you have to
                    know the user names of your collaborators in advance.
                </p>
                <input id="unitCollaborationEditForm_collaborator" type="text" class="input" placeholder="Username" />
                <button id="unitCollaborationEditForm_addbutton" class="btn" >Add</button>
            </div>
            <div class="span8" id="unitCollaborationEditForm_usernames"></div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn">Update</button>
        <button type="button" data-dismiss="modal" class="btn">Close</button>
    </div>
</div>

app/templates/windowEditEvent.html
<!-- View for editing events -->
<div id="eventEditor" class="eventModel editorView">
    <div class="row-fluid ">

        <div class="span12 unitInfo">

                <ul class="nav nav-tabs" id="eventEditTabs_Headers">
                    <li class="active"><a href="#eventEdit_tab1" data-toggle="tab">Basic information</a></li>
                    <li><a href="#eventEdit_tab2" data-toggle="tab">Units and routing</a></li>
                    <li><a href="#eventEdit_tab3" data-toggle="tab">Topics and categories</a></li>
                </ul>
                <div class="tab-content" id="eventEditTabs_Containers">
                    <div class="tab-pane active" id="eventEdit_tab1">

                        <div class="row-fluid">
                            <div class="span6">
                                <h4>Title</h4>
                                <input id="eEditor_Title_test" type="text" class="input text eEditor_Title" data-bind="value: content" />

                                <h4>Significance</h4>
                                <div id="eEditor_Significance_test" data-bind="raty:significance"></div>

                                <h4>Start</h4>
                                <div id="eventIEditor_startDatetime_test" data-bind="connect_bigdate:start"></div>

                                <h4>Incertitude</h4>
                                <select data-bind="value: incertitude">
                                    <option value="0" selected="selected">Exact Millenium of event cannot be specified</option>
                                    <option value="1">Exact Century of event cannot be specified</option>
                                    <option value="2">Exact Decade of event cannot be specified</option>
                                    <option value="3">Exact Year of event cannot be specified</option>
                                    <option value="4">Exact Month of event cannot be specified</option>
                                    <option value="5">Exact Day of event cannot be specified</option>
                                    <option value="6">Exact Hour of event cannot be specified</option>
                                    <option value="7">Exact Minute of event cannot be specified</option>
                                    <option value="8">Exact Second of event cannot be specified</option>
                                    <option value="9">All details of event are known</option>
                                </select>
                            </div>
                            <div class="span6">
                                <h4>Wikipedia</h4>
                                <input id="eEditor_Wikilink_test" type="text" class="input text eEditor_Wikilink" data-bind="value:wikilink" placeholder="Wikipedia URL" />

                                <h4>Event general icon</h4>
                                <input id="eEditor_Filename_test" ctype="text" data-bind="value: filename" class="input movImgURL text eEditor_Filename" /><img id="eventImg_smallimg" data-bind="attr:{src: filename()}" style="max-width:30px;max-height:30px;" /><form style="display:inline;" id="eventImg_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="eventImg") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_eventImg" name="unitMovementImage_eventImg"></form>

                                <h4>End</h4>
                                <div id="eventIEditor_endDatetime_test" data-bind="connect_bigdate:end"></div>

                                <h4>Expert agreement</h4>
                                <select data-bind="value: incertitude_type">
                                    <option value="0">No discourse concerning this event</option>
                                    <option value="1">Majority of historians disagree with this version of event (>50%)</option>
                                    <option value="2">Bigger minority of historians disagree with this version of event (26-50%)</option>
                                    <option value="3">Smaller minority of historians disagree with this version of event (10-25%)</option>
                                    <option value="4">Only few historians disagree with this version of event (<10%)</option>
                                    <option value="5">This version of event is without any controversy amongst historians</option>
                                </select>
                            </div>
                        </div>

                        <h4>Description</h4>
                        <textarea id="eEditor_Description_test" class="input text eEditor_Description" data-bind="value:description" style="width: 95%; height: 180px;"></textarea>

                        Public specified: <input type="radio" name="eventPublicPrivate" value="0" data-bind="checked: visibility_type" />
                        Public unspecified:  <input type="radio" name="eventPublicPrivate" value="1" data-bind="checked: visibility_type" />
                        Public fictional: <input type="radio" name="eventPublicPrivate" value="2" data-bind="checked: visibility_type" />
                        Private: <input type="radio" name="eventPublicPrivate" value="3" data-bind="checked: visibility_type" />

                        <button type="button" id="eventIEditor_CooperationEditor" class="btn" data-bind="visible:updateMode()">Collaborators</button>
                        <button class="btn" id="eventIEditor_SaveButton_test" type="button" data-bind="click:save">Save and close</button>
                        <button class="btn" id="eventIEditor_DeleteButton" type="button" data-bind="click:deleteEventAndClose, visible:id() > -1">Delete</button>
                        <button class="btn" id="eventIEditor_CancelButton" type="button" data-bind="click:cancel">Cancel</button>

                    </div>
                    <div class="tab-pane" id="eventEdit_tab2">
                        <h3>Selected units (<a id="btnUnitFinder_test" style="cursor:pointer;">Add unit</a>)</h3>
                        <h4 data-bind="visible:data().length == 0">No units selected!</h4>
                        <div id="eEditor_SelUnitlist_test" data-bind="foreach:data" style="height:560px;overflow:auto;">
                            <div class="unit" data-bind="attr:{id:eventunit}">
                                <div style="float:left;margin-left:5px;">
                                    <h4 data-bind="text:unit_title"></h4>
                                    <img data-bind="attr:{src:image}" style="max-height: 50px; max-width: 50px; margin-left: 5px;" />
                                    <input type="text" class="input" data-bind="value:unit_label" placeholder="Descriptive unit label" />
                                    <input type="text" class="input-mini" data-bind="value:zoom_min" placeholder="Zoom min" />
                                    <input type="text" class="input-mini" data-bind="value:zoom_max" placeholder="Zoom max" />
                                    <button class="btn" data-bind="click:$parent.unitRoute">Route</button>
                                    <button class="btn" data-bind="click:$parent.deleteUnit">Remove</button>
                                </div>
                                <div style="float:left;width:1px;height:1px;visibility:hidden;overflow:hidden" id="">
                                </div>
                            </div>
                            <div style="clear:both"></div>
                        </div>
                    </div>
                    <div class="tab-pane" id="eventEdit_tab3">
                        <h4>Topics</h4>

                        <div data-bind="visible: !private_event()" class="eventEdit_topic_listing_container" id="eventEdit_topic_public_listing_container">{{ topic_public_selectors|safe }}</div>
                        <div data-bind="visible: private_event()" class="eventEdit_topic_listing_container" id="eventEdit_topic_private_listing_container">{{ topic_private_selectors|safe }}</div>

                        <div class="hideMe">
                            <h4>Assign categories</h4>
                            <p>Find:</p>
                            <input type="text" id="eEditor_CatFindText" />
                            <p>Search results:</p>
                            <div id="eEditor_FoundCats"></div>
                            <p>Selected categories:</p>
                            <div id="eEditor_SelCats"></div>
                        </div>

                    </div>

            </div>
        </div>

        <div class="span12 unitRoute">
            <h4>Unit routing</h4>
            <p>Activate dragging <input type="checkbox" id="dragSel" onchange="activeDrag();"/></p>
            <p>Click the map for adding new waypoints. Old waypoints can be dragged.</p>
            <div class="row-fluid" data-bind="foreach:{data:selectedItem}">
                <div class="span12" id="editor_route" data-bind="foreach:{data:datapoints,afterAdd : $parent.routeDates}">
                    <div class="row-fluid routeRow">
                        <span class="span1" style="font-weight: bold;" data-bind="text:$index"></span>
                        <a href="#" data-bind="click:$root.removeRoutePoint"><span class="add-on"><i class="icon-trash"></i>REMOVE</span></a>
                        <div data-bind="connect_bigdate:time" class="routeDate"></div>
                    </div>
                </div>
                <button data-bind="click:$parent.saveRoute">Save</button>
            </div>
        </div>

    </div>
</div>

app/templates/windowEditPlaylist.html
<!-- Window for editing a playlist -->
<div id="playlistIEditor_Editor" class="modal hide fade" tabindex="-1" data-width="80%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Playlist editor</h3>
    </div>
    <div class="modal-body">
    <div class="row-fluid">
        <div class="span6">
            <label for="pEditor_Title">Title</label>
            <input id="pEditor_Title" type="text" class="input text pEditor_Title" placeholder="Playlist title" />
            <label for="pEditor_Imageurl">Playlist icon</label>
            <input id="pEditor_Imageurl" type="text" class="input text pEditor_Imageurl movImgURL" /><img id="playlistIcon_img" src="" style="max-width:30px;max-height:30px;" /><form style="display:inline;" id="playlistIcon_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="playlist") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_playlist" name="unitMovementImage_playlist"></form>
            <label for="pEditor_Description">Description</label>
            <textarea id="pEditor_Description" class="input text pEditor_Description" title="Playlist description"></textarea>
        </div>
        <div class="span6">
            <h4>Selected events <button class="btn btn-primary" id="btnEventFinderForPlaylist">Add event</button></h4>
            <div id="pEditor_SelectedEvents" style="overflow-y: auto; height: 290px;"></div>
        </div>
    </div>
    </div>
    <div class="modal-footer">
        <a id="pEdit_Export" class="btn" target="_blank" href="#">Export</a>
        <button type="button" id="playlistIEditor_btnSave" data-dismiss="modal" class="btn">Save</button>
        <button type="button" data-dismiss="modal" class="btn">Cancel</button>
    </div>
</div>

app/templates/windowEditUnit.html
<!-- Unit information edit popup window -->
<div id="unitEModal" class="modal hide fade unitModel" tabindex="-1" data-width="80%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 id="ueInfo_Title" data-bind="text:validatedTitle">Unit title</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <div class="span3">
                <h4>Title</h4>
                <input type="text" id="eUnit_Title" data-bind="value:title" placeholder="Unit title"/>
                <h4>Description <img src="" id="ueInfo_Image" style="max-height: 20px; margin-left: 10px;" data-bind="attr:{src:filename}" /></h4>
                <textarea id="eUnit_Description" data-bind="value:description" placeholder="Unit description"></textarea>
                <h4>Wikipedia</h4>
                <input type="text" id="eUnit_Wikilink" data-bind="value:wikilink" placeholder="Wikipedia URL" />
            </div>
            <div class="span6">
                <h4>Appears</h4>
                <div id="eUnit_appearsDatetime" data-bind="connect_bigdate:appears"></div>
                <h4>Disappears</h4>
                <div id="eUnit_disappearsDatetime" data-bind="connect_bigdate:disappears"></div>
                <h4>Location</h4>
                <input type="text" id="eUnit_Location" data-bind="value:location" placeholder="Location of the unit" />
                <h4>Unit general icon</h4>
                <input type="text" class="movImgURL" id="eUnit_Filename" data-bind="value:filename"/><img id="eUnit_movementImage_filename_img" data-bind="attr:{src: filename()}" style="max-width:30px;max-height:30px;" /><form style="display:inline;" id="eUnit_movementImage_filename_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="filename") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_filename" name="unitMovementImage_filename"></form>
            </div>
            <div class="span3">
                <h4>Movement images</h4>
                <table>
                    <tr><td>North: </td><td><input type="text" class="movImgURL" placeholder="North" id="eUnit_movementImage_north" data-bind="value:imageData().north" /><img id="eUnit_movementImage_north_img" data-bind="attr:{src: imageData().north}" style="max-width:30px;max-height:30px;" /></td><td><form style="display:inline;" id="eUnit_movementImage_north_image_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="north") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_north" name="unitMovementImage_north"></form></td></tr>
                    <tr><td>North-east: </td><td><input type="text" class="movImgURL" placeholder="North east" id="eUnit_movementImage_north_east" data-bind="value:imageData().north_east" /><img id="eUnit_movementImage_north_east_img" data-bind="attr:{src: imageData().north_east}" style="max-width:30px;max-height:30px;" /></td><td><form style="display:inline;" id="eUnit_movementImage_north_east_image_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="north_east") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_north_east" name="unitMovementImage_north_east"></form></td></tr>
                    <tr><td>East: </td><td><input type="text" class="movImgURL" placeholder="East" id="eUnit_movementImage_east" data-bind="value:imageData().east" /><img id="eUnit_movementImage_east_img" data-bind="attr:{src: imageData().east}" style="max-width:30px;max-height:30px;" /></td><td><form style="display:inline;" id="eUnit_movementImage_east_image_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="east") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_east" name="unitMovementImage_east"></form></td></tr>
                    <tr><td>South-east: </td><td><input type="text" class="movImgURL" placeholder="South east" id="eUnit_movementImage_south_east" data-bind="value:imageData().south_east" /><img id="eUnit_movementImage_south_east_img" data-bind="attr:{src: imageData().south_east}" style="max-width:30px;max-height:30px;" /></td><td><form style="display:inline;" id="eUnit_movementImage_south_east_image_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="south_east") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_south_east" name="unitMovementImage_south_east"></form></td></tr>
                    <tr><td>South: </td><td><input type="text" class="movImgURL" placeholder="South" id="eUnit_movementImage_south" data-bind="value:imageData().south" /><img id="eUnit_movementImage_south_img" data-bind="attr:{src: imageData().south}" style="max-width:30px;max-height:30px;" /></td><td><form style="display:inline;" id="eUnit_movementImage_south_image_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="south") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_south" name="unitMovementImage_south"></form></td></tr>
                    <tr><td>South-west: </td><td><input type="text" class="movImgURL" placeholder="South west" id="eUnit_movementImage_south_west" data-bind="value:imageData().south_west" /><img id="eUnit_movementImage_south_west_img" data-bind="attr:{src: imageData().south_west}" style="max-width:30px;max-height:30px;" /></td><td><form style="display:inline;" id="eUnit_movementImage_south_west_image_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="south_west") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_south_west" name="unitMovementImage_south_west"></form></td></tr>
                    <tr><td>West: </td><td><input type="text" class="movImgURL" placeholder="West" id="eUnit_movementImage_west" data-bind="value:imageData().west" /><img id="eUnit_movementImage_west_img" data-bind="attr:{src: imageData().west}" style="max-width:30px;max-height:30px;" /></td><td><form style="display:inline;" id="eUnit_movementImage_west_image_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="west") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_west" name="unitMovementImage_west"></form></td></tr>
                    <tr><td>North-west: </td><td><input type="text" class="movImgURL" placeholder="North west" id="eUnit_movementImage_north_west" data-bind="value:imageData().north_west" /><img id="eUnit_movementImage_north_west_img" data-bind="attr:{src: imageData().north_west}" style="max-width:30px;max-height:30px;" /></td><td><form style="display:inline;" id="eUnit_movementImage_north_west_image_form" action='{{ url_for("event_datasource.uploadUnitImage",dir="north_west") }}' method="post" enctype="multipart/form-data"><input style="color:transparent;width:120px;" type="file" id="unitMovementImage_north_west" name="unitMovementImage_north_west"></form></td></tr>
                </table>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" id="unitCooperationEditor" class="btn" data-bind="visible:updateMode()">Collaborators</button>
        <button type="button" id="unitUSave" class="btn" data-bind="text:mode,visible:originalAuthor()">Update</button>
        <button type="button" id="unitUDelete" class="btn" data-bind="visible:originalAuthor() && id()>-1">Delete</button>
        <button type="button" data-dismiss="modal" class="btn">Close</button>
    </div>
</div>

app/templates/windowInfoPlaylist.html
<!-- Window for showing playlist information -->
<div id="playlistInfo" class="modal hide fade" tabindex="-1" data-width="80%">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Playlist information</h3>
    </div>
    <div class="modal-body">
        <div class="row-fluid">
            <div class="span12">
                <!-- Content -->
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" data-dismiss="modal" class="btn">Close</button>
    </div>
</div>